In [1]:
from google.colab import files
uploaded = files.upload()

Saving Parkinson_Multiple_Sound_Recording.rar to Parkinson_Multiple_Sound_Recording (1).rar

In [2]:
!apt-get -q install unrar

Reading package lists...
Building dependency tree...
Reading state information...
unrar is already the newest version (1:6.1.5-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [3]:
import os

for root, dirs, files in os.walk(".", topdown=True):
    for name in files:
        print(os.path.join(root, name))

./Parkinson_Multiple_Sound_Recording.rar
./Parkinson_Multiple_Sound_Recording (1).rar
./.config/active_config
./.config/gce
./.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
./.config/.last_survey_prompt.yaml
./.config/default_configs.db
./.config/config_sentinel
./.config/.last_update_check.json
./.config/.last_opt_in_prompt.yaml
./.config/logs/2026.01.16/14.24.13.071214.log
./.config/logs/2026.01.16/14.23.31.981136.log
./.config/logs/2026.01.16/14.24.29.392089.log
./.config/logs/2026.01.16/14.24.28.646070.log
./.config/logs/2026.01.16/14.24.18.954466.log
./.config/logs/2026.01.16/14.24.03.314209.log
./.config/configurations/config_default
./sample_data/README.md
./sample_data/anscombe.json
./sample_data/california_housing_train.csv
./sample_data/mnist_test.csv
./sample_data/mnist_train_small.csv
./sample_data/california_housing_test.csv

In [4]:
!apt-get -q install unrar

Reading package lists...
Building dependency tree...
Reading state information...
unrar is already the newest version (1:6.1.5-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [5]:
!unrar x "Parkinson_Multiple_Sound_Recording.rar"

UNRAR 6.11 beta 1 freeware      Copyright (c) 1993-2022 Alexander Roshal


Extracting from Parkinson_Multiple_Sound_Recording.rar

Extracting  test_data.txt                                                 13%  OK
Extracting  train_data.txt                                                48% 83%100%  OK
All OK

In [6]:
!ls

'Parkinson_Multiple_Sound_Recording (1).rar'   sample_data     train_data.txt
 Parkinson_Multiple_Sound_Recording.rar        test_data.txt

In [7]:
import pandas as pd

train = pd.read_csv("/content/train_data.txt", header=None)
test = pd.read_csv("/content/test_data.txt", header=None)

In [8]:
print("Train shape:", train.shape)
print("Test shape:", test.shape)

Train shape: (1040, 29)
Test shape: (168, 28)

take only train set and split it into train + test

In [9]:
import pandas as pd


train = pd.read_csv("/content/train_data.txt", sep=",", header=None)

train.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,1,1.488,0.000090,0.900,0.794,2.699,8.334,0.779,4.517,4.609,...,187.576,160,159,0.006065,0.000416,0.000,0,0.000,23,1
1,1,0.728,0.000038,0.353,0.376,1.059,5.864,0.642,2.058,3.180,...,234.505,170,169,0.005181,0.000403,2.247,0,0.000,23,1
2,1,1.220,0.000074,0.732,0.670,2.196,8.719,0.875,4.347,5.166,...,211.442,1431,1427,0.006071,0.000474,10.656,1,0.178,23,1
3,1,2.502,0.000123,1.156,1.634,3.469,13.513,1.273,5.263,8.771,...,220.230,94,92,0.004910,0.000320,0.000,0,0.000,23,1
4,1,3.509,0.000167,1.715,1.539,5.145,9.112,1.040,3.102,4.927,...,225.162,117,114,0.004757,0.000380,18.182,1,13.318,23,1

In [10]:
print("Shape of dataset:", train.shape)

Shape of dataset: (1040, 29)

In [11]:
X = train.iloc[:, :-1]   # all columns except last
y = train.iloc[:, -1]    # last column

print(X.shape, y.shape)

(1040, 28) (1040,)

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,        # 80% train, 20% test
    stratify=y,           # keeps class balance
    random_state=42,
    shuffle=True
)

In [13]:
print("Training class distribution:")
print(y_train.value_counts())

print("\nTest class distribution:")
print(y_test.value_counts())

Training class distribution:
28
0    416
1    416
Name: count, dtype: int64

Test class distribution:
28
1    104
0    104
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
import pandas as pd

# Convert numpy arrays → DataFrames
X_train_scaled_df = pd.DataFrame(X_train)
X_test_scaled_df = pd.DataFrame(X_test)

y_train_df = pd.DataFrame(y_train).reset_index(drop=True)
y_test_df = pd.DataFrame(y_test).reset_index(drop=True)

In [16]:
train_scaled_full = pd.concat([X_train_scaled_df, y_train_df], axis=1)
test_scaled_full = pd.concat([X_test_scaled_df, y_test_df], axis=1)

train_scaled_full.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,0.048087,0.017933,0.907806,0.435800,0.238058,0.436142,0.914735,0.797477,1.418235,0.371826,...,-1.000489,-0.441248,-0.424815,1.780641,-0.538149,-1.133063,-0.723403,-0.830896,-0.759070,0
1,-0.386787,0.245961,1.245193,-0.287846,-0.492513,-0.287490,0.042349,0.003537,0.253163,0.048183,...,-0.979245,-0.579472,-0.570022,1.733012,0.643888,0.945244,-0.109875,0.964839,2.651963,1
2,-0.995611,-0.670242,-0.171279,-0.841970,-0.593875,-0.842310,-0.742342,-0.704828,-0.907139,-0.733386,...,-0.903767,-0.533397,-0.517220,1.843580,-0.159174,-0.896833,-0.723403,-0.830896,-0.127397,1
3,-0.299812,-0.875467,-0.757392,-0.929910,-0.722968,-0.929541,-0.180462,-0.205645,-0.623283,-0.366013,...,-0.769283,-0.335934,-0.319211,0.608303,-0.547054,-1.345962,-0.723403,-0.830896,-0.506401,1
4,-1.691410,0.777440,0.159088,0.725047,0.853880,0.725029,0.654758,0.393376,0.743522,0.778597,...,0.085449,-0.197709,-0.187204,-0.993681,-0.439594,0.381856,-0.109875,0.391232,0.630610,1

In [17]:
train_scaled_full.to_csv("parkinsons_train_scaled.csv", index=False)
test_scaled_full.to_csv("parkinsons_test_scaled.csv", index=False)

Before i download csv files , i just want to make sure that our data is not corrupted in the process ( sanity check)

In [18]:
print("Train shape:", train_scaled_full.shape)
print("Test shape:", test_scaled_full.shape)

Train shape: (832, 29)
Test shape: (208, 29)

In [19]:
print("Missing values in train:\n", train_scaled_full.isnull().sum().sum())
print("Missing values in test:\n", test_scaled_full.isnull().sum().sum())

Missing values in train:
 0
Missing values in test:
 0

In [20]:
import numpy as np

print("Train infinite values:", np.isinf(train_scaled_full.values).sum())
print("Test infinite values:", np.isinf(test_scaled_full.values).sum())

Train infinite values: 0
Test infinite values: 0

In [21]:
print("Train label distribution:\n", train_scaled_full.iloc[:, -1].value_counts())
print("\nTest label distribution:\n", test_scaled_full.iloc[:, -1].value_counts())

Train label distribution:
 28
0    416
1    416
Name: count, dtype: int64

Test label distribution:
 28
1    104
0    104
Name: count, dtype: int64

In [22]:
print("Feature means (train):")
print(train_scaled_full.iloc[:, :-1].mean().round(2).head())

print("\nFeature stds (train):")
print(train_scaled_full.iloc[:, :-1].std().round(2).head())

Feature means (train):
0    0.0
1   -0.0
2    0.0
3   -0.0
4    0.0
dtype: float64

Feature stds (train):
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

In [23]:
train_scaled_full.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
637,1.700609,-1.285332,-1.287719,-1.120622,-1.059566,-1.120603,-1.856397,-2.228527,-1.526648,-1.327866,...,-0.731454,0.427593,0.446425,0.332287,-0.974102,-1.345962,-0.723403,-0.830896,-0.759070,0
481,-0.734686,-0.134085,0.467185,0.125364,0.183552,0.125358,0.104230,0.150915,0.313819,-0.022362,...,-0.962586,-0.539979,-0.523820,1.319185,-0.760266,-0.747123,-0.723403,-0.830896,1.199116,1
335,1.352710,-0.742158,-0.913853,-0.715888,-0.676112,-0.715878,0.123454,0.100997,0.221131,-0.323109,...,-0.105365,-0.145052,-0.134402,-0.693871,-0.464437,-0.307958,-0.109875,0.659889,-0.759070,0
776,-1.256535,-1.337369,-1.351794,-1.130157,-1.051916,-1.129785,-1.412239,-1.734098,-1.047534,-1.045271,...,-0.737086,3.685744,3.713577,0.278545,-1.041158,-1.345962,-0.723403,-0.830896,2.083458,1
514,-0.560737,0.122592,-0.085159,-0.070646,0.241883,-0.070648,-0.421582,-0.131956,-0.644410,-0.465231,...,-0.131619,-0.131888,-0.127802,-0.501273,0.401614,0.109456,0.503653,-0.272530,-0.506401,1

In [24]:
from google.colab import files

files.download("parkinsons_train_scaled.csv")
files.download("parkinsons_test_scaled.csv")

quick sanity check again

In [25]:
import pandas as pd

train_df = pd.read_csv("parkinsons_train_scaled.csv")
test_df = pd.read_csv("parkinsons_test_scaled.csv")

In [26]:
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (832, 29)
Test shape: (208, 29)

In [27]:
print("Missing values (train):", train_df.isnull().sum().sum())
print("Missing values (test):", test_df.isnull().sum().sum())

Missing values (train): 0
Missing values (test): 0

In [28]:
print("Train label distribution:\n", train_df.iloc[:, -1].value_counts())
print("\nTest label distribution:\n", test_df.iloc[:, -1].value_counts())

Train label distribution:
 28
0    416
1    416
Name: count, dtype: int64

Test label distribution:
 28
1    104
0    104
Name: count, dtype: int64

In [29]:
print("Train feature mean (first 5):")
print(train_df.iloc[:, :-1].mean().head())

print("\nTrain feature std (first 5):")
print(train_df.iloc[:, :-1].std().head())

Train feature mean (first 5):
0    1.590608e-16
1   -1.494531e-16
2    1.302377e-16
3   -1.708035e-17
4    3.992533e-16
dtype: float64

Train feature std (first 5):
0    1.000602
1    1.000602
2    1.000602
3    1.000602
4    1.000602
dtype: float64

In [30]:
train_df.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
415,-1.517460,-0.659133,-0.906289,-0.323869,-0.404538,-0.324219,-0.174421,-0.089169,0.090959,-0.041133,...,0.020982,0.078740,0.096609,-0.922724,-0.574343,-0.903732,-0.723403,-0.830896,1.704454,1
202,-0.125863,0.520763,0.258842,0.449574,1.146491,0.449209,0.437440,0.293539,-0.041939,0.445053,...,-0.061659,-0.303023,-0.299410,-0.526750,0.042420,0.022792,0.503653,0.803129,0.820112,1
428,-0.212837,2.298793,1.359493,3.017829,3.273180,3.017413,1.221947,0.585918,3.185097,2.424658,...,2.072536,-0.526815,-0.537021,-0.949173,0.820029,2.394723,-0.109875,0.629406,1.199116,1
548,-1.517460,-0.296628,-0.655991,-0.119383,-0.117665,-0.119385,-0.345969,0.003537,-0.118270,-0.250707,...,0.147272,-0.131888,-0.114601,-1.004700,-0.269700,-1.345962,-0.723403,-0.830896,1.704454,1
487,-1.169561,0.386870,0.564031,0.521621,0.693231,0.521960,0.654392,0.614443,0.316885,0.415969,...,1.744224,0.184054,0.182413,0.196160,0.436840,0.564431,1.117182,1.861222,1.704454,1